Milestone 3
tiagoit/mv-rails-06-finalproject pull request #3
Opened 2019-11-28 16:15 UTC by ferreirati

- Secure all routes but auth ones.
- Home page with Users/ Posts listing
- Create post route
- User profile route

2019-11-28 21:48 UTC, mosaaleb commented on app/controllers/posts_controller.rb
> +  def index
- [ ] Index displays posts in a timeline (recent to older) -- We can achieve this by using [default scope](https://apidock.com/rails/ActiveRecord/Base/default_scope/class) in `post.rb`. An example could be [this](https://stackoverflow.com/questions/3393687/default-sort-order-for-a-rails-model).

- [ ] **[OPTIONAL]** We could just say `@posts = current_user.posts`

2019-11-28 22:08 UTC, mosaaleb requested changes
## Well done @ferreirati :clap:

- [x] This is a collaborative project, but I can only only you in the commit history, have you reached the student success about this?

- [x] UsersController#index displays all users -- Let's add users controller to list all users.


- [x] We still haven't added any tests yet. Please lets add rspec **model** tests, and capybara **integration** tests for post creation.


#### Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2019-11-28 22:08 UTC, mosaaleb commented on app/controllers/posts_controller.rb
> +    @posts = Post.where(user_id: current_user.id)
- [x] Index displays posts in a timeline (recent to older) -- We can achieve this by using [default scope](https://apidock.com/rails/ActiveRecord/Base/default_scope/class) in `post.rb`. An example could be [this](https://stackoverflow.com/questions/3393687/default-sort-order-for-a-rails-model).

- [ ] **[OPTIONAL]** We could just say `@posts = current_user.posts`

2019-11-28 22:08 UTC, mosaaleb commented on app/controllers/posts_controller.rb
> +  def edit
- [ ] **[OPTINOAL]** Let's continue implementing edit and delete feature for posts.

2019-11-28 22:08 UTC, mosaaleb commented on app/views/posts/_post.html.erb
> +<%= post.content %>
- [ ] Post is always displayed with content and author -- Let's add the author

2019-11-30 05:29 UTC, Ispirett approved these changes
# status Approved :+1:  :1st_place_medal: 
Great work!! done here folks @ferreirati  @oscardelalanza

2019-11-30 05:58 UTC, merged